export const SYSTEM_NOTIFICATION_TYPES = {
  DELETE_TEXT: 'DELETE_TEXT',
  DELETE_MEDIA: 'DELETE_MEDIA',
};

export const SYSTEM_MESSAGE_TYPES = {
  GREETING: 'GREETING',
  WELCOME: 'WELCOME',
  LEAVE_GROUP: 'LEAVE_GROUP',
};
